name: Test maximum
image: pytest
# if cmd not specifed, used image cmd
#cmd: "./check.sh"
#cmd: "pwd; ls -la"
cmd: bash check.sh
points: 100
targetpath: /opt/sandbox/answer.py
inject: test_max.py:/opt/sandbox/test_max.py,README.md:/opt/sandbox/README.md
