web:
  hostname: 0.0.0.0
  usehttp: true
  usehttps: false
  httpport: 8000
  httpsport: 0
  certfile: ""
  keyfile: ""
  credfile: ""
  googleoauth:
    secret: secret
    sessionname: oauth
    credfile: clientid.google.json
model:
  localchallengespath: etc/challenges
checker:
  endpoint: unix:///var/run/docker.sock
  timeout: 0
  threads: 0
database:
  driver: sqlite3