web:
  hostname: domain.com
  listen: 0.0.0.0
  usehttp: true
  usehttps: false
  httpport: 8000
  httpsport: 0
  certfile: ""
  keyfile: ""
  credfile: ""
  googleoauth:
    secret: secret
    sessionname: oauth
    oauthclientid: change_me
    oauthsecret: change_me
    sessionduration: 86400
model:
  localtestfiles: ./data
checker:
  endpoint: unix:///var/run/docker.sock
  challengespath: etc/challenges
  imagespath: etc/images
  timeout: 60000
  threads: 4
database:
  driver: sqlite3
  dsn: _db.sqlite3
